# Generated by Django 6.0 on 2026-01-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_lastname', models.CharField(max_length=50)),
                ('client_firstname', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_address', models.TextField()),
                ('client_due_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
