# Generated by Django 6.0 on 2026-01-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_client_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_nom',
            new_name='client_familyname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_prenom',
            new_name='client_firstname',
        ),
    ]
