# Generated by Django 5.2.8 on 2026-01-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='city',
            new_name='dest_city',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='country',
            new_name='dest_country',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='zone',
            new_name='dest_zone',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='description',
            new_name='st_description',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='name',
            new_name='st_name',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='volume_rate',
            new_name='st_volume_rate',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='weight_rate',
            new_name='st_weight_rate',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='is_active',
        ),
    ]
