@startuml

skinparam linetype ortho

entity "Agent" as agent {
}

entity "PasswordResetCode" as PasswordResetCode {
}

entity "Vehicle" as vehicle {
}

entity "Shipment" as shipment {
}


entity "Destination" as destination {
}

entity "ServiceType" as service_type {
}

entity "Payment" as payment {
}
entity "Invoice" as invoice {
}
entity "Incident" as incident {
}
entity "Client" as client {
}
entity "Driver" as driver {
}
entity "Tour" as tour {
}
entity "Complaint" as complaint {
}
shipment -- client
shipment -- service_type
shipment -- destination
shipment -- driver
shipment -- vehicle
PasswordResetCode -- agent
payment -- client
payment -- invoice
invoice -- shipment
invoice -- client
incident -- shipment
incident -- tour
tour -- driver
tour -- vehicle
tour -- shipment
complaint -- client
complaint -- invoice
complaint -- shipment

@enduml