# Generated by Django 6.0 on 2026-01-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Damage', 'Damage'), ('Delay', 'Delay'), ('Lost', 'Lost'), ('Theft', 'Theft'), ('Address Issue', 'Address Issue'), ('System Error', 'System Error'), ('Other', 'Other')], max_length=50)),
                ('incident_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('incident_description', models.TextField()),
                ('incident_time', models.DateTimeField()),
                ('incident_created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.shipment')),
            ],
        ),
    ]
