# Generated by Django 5.2.8 on 2026-01-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DeliveryTour', '0001_initial'),
        ('Incident', '0001_initial'),
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.shipment'),
        ),
        migrations.AddField(
            model_name='incident',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryTour.deliverytour'),
        ),
    ]
