# Generated by Django 6.0 on 2026-01-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incident', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='description',
            new_name='incident_description',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='location',
            new_name='incident_location',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='severity',
            new_name='incident_severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reported_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved_at',
        ),
    ]
