# Generated by Django 6.0 on 2026-01-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Drivers', '0001_initial'),
        ('Invoice', '0001_initial'),
        ('Services', '0001_initial'),
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_tracking_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('shipment_total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipment_total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipment_status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('at_sorting_center', 'At Sorting Center'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='pending', max_length=50)),
                ('shipment_expected_delivery_date', models.DateField(blank=True, null=True)),
                ('shipment_delivery_date', models.DateField(blank=True, null=True)),
                ('shipment_notes', models.TextField(blank=True, null=True)),
                ('shipment_created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.destination')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Drivers.driver')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invoice.invoice')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.servicetype')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicles.vehicle')),
            ],
        ),
    ]
