# Generated by Django 6.0 on 2026-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='created_at',
            new_name='shipment_created_at',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_date',
            new_name='shipment_delivery_date',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='description',
            new_name='shipment_description',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='status',
            new_name='shipment_status',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='updated_at',
            new_name='shipment_updated_at',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='volume',
            new_name='shipment_volume',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='weight',
            new_name='shipment_weight',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
