# Generated by Django 5.2.8 on 2026-01-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=50)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_shipments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drivers.driver')),
            ],
        ),
    ]
