# Generated by Django 5.2.8 on 2026-01-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DeliveryTour', '0001_initial'),
        ('Shipment', '0001_initial'),
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytour',
            name='shipments',
            field=models.ManyToManyField(to='Shipment.shipment'),
        ),
        migrations.AddField(
            model_name='deliverytour',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle'),
        ),
    ]
