# Generated by Django 6.0 on 2026-01-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryTour', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytour',
            old_name='distance',
            new_name='tour_distance',
        ),
        migrations.RenameField(
            model_name='deliverytour',
            old_name='duration',
            new_name='tour_duration',
        ),
        migrations.RenameField(
            model_name='deliverytour',
            old_name='fuel_consumption',
            new_name='tour_fuel_consumption',
        ),
        migrations.RenameField(
            model_name='deliverytour',
            old_name='status',
            new_name='tour_status',
        ),
        migrations.RemoveField(
            model_name='deliverytour',
            name='completed_shipments',
        ),
        migrations.RemoveField(
            model_name='deliverytour',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliverytour',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deliverytour',
            name='total_volume',
        ),
        migrations.RemoveField(
            model_name='deliverytour',
            name='total_weight',
        ),
    ]
