# Generated by Django 6.0 on 2026-01-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_issue_date', models.DateField()),
                ('invoice_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_tax_amount', models.DecimalField(decimal_places=2, default=19, max_digits=10)),
                ('invoice_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue')], default='pending', max_length=50)),
                ('invoice_created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client')),
            ],
        ),
    ]
