# Generated by Django 5.2.8 on 2026-01-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invoice', '0001_initial'),
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipments',
            field=models.ManyToManyField(to='Shipment.shipment'),
        ),
    ]
