# Generated by Django 6.0 on 2026-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='issue_date',
            new_name='invoice_issue_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='notes',
            new_name='invoice_notes',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='invoice_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_due_date',
            field=models.DateField(null=True),
        ),
    ]
