# Generated by Django 6.0 on 2026-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle')], default='truck', max_length=50)),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_license_plate', models.CharField(max_length=50, unique=True)),
                ('vehicle_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=50)),
                ('vehicle_fuel_mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_start_date', models.DateField(blank=True, null=True)),
                ('vehicle_end_date', models.DateField(blank=True, null=True)),
                ('vehicle_active', models.BooleanField(default=True)),
                ('vehicle_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
