# Generated by Django 6.0 on 2026-01-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_description', models.TextField()),
                ('package_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='Shipment.shipment')),
            ],
        ),
    ]
