# Generated by Django 5.2.8 on 2026-01-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_client_balance'),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('delivery', 'Delivery Issue'), ('billing', 'Billing Issue'), ('service', 'Service Quality'), ('damage', 'Damaged Goods'), ('delay', 'Delivery Delay'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('actual_resolution_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50)),
                ('priority', models.IntegerField(default=3)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client')),
            ],
        ),
    ]
