# Generated by Django 5.2.8 on 2026-01-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Complaint', '0001_initial'),
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invoice.invoice'),
        ),
    ]
