# Generated by Django 6.0 on 2026-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='category',
            new_name='complaint_category',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='complaint_description',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='status',
            new_name='complaint_status',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='actual_resolution_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='target_resolution_date',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=50),
        ),
    ]
